# gh pages build does not use threads / mutex's
# this offers wider browser support.
name: deploy_pages

on:
  push:
    branches: [ "master" ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11

      - name: Cmake Build
        run: |
          embuilder build zlib
          # embuilder build zlib --lto
          # embuilder build zlib --lto=thin
          cmake --preset emsdk
          cmake --build --preset emsdk --parallel 4

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/emsdk/bin # The folder the action should deploy.
          # single-commit: true # Start branch with no history
